esphome:
  name: ikea-vindriktning-01

esp8266:
  # The name of your board, see https://registry.platformio.org/platforms/platformio/espressif8266/boards
  board: d1_mini_lite
  
# Enable logging
logger:
  # Set to 0 to receive data
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "<REDACTED>"

ota:
  password: "<REDACTED>"

wifi:
  manual_ip:  # Custom
      # Set this to the IP of the ESP
    static_ip: 192.168.0.25
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ikea-Vindriktning-01"
    password: "<REDACTED>"

captive_portal:
    

# Custom modifs
uart:
  # Use the pin to which the data is sent
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
